general:
  data:
    data_path:
    excluding_columns: ['series_id', 'timestamp', 'step', 'night', 'event']
  test_data:
    data_path: ...

model:
  cnn:
    activation: ...
    normalization: ...
    polling: ...
    out_features: ...
    pooling_sizes: ...
    kernel_sizes: ...
    strides: ...
    dilations: ...
    dropout_rates: ...
    fc_outputs: ...
    fc_dropout_rates: ...

train:
  data:
    scaler: 'StandardScaler'
  model: 'cnn'
  n_features: ...
  seq_len: ...
  batch_size: ...
  optimizer: ...
  criterion: ...
  epochs: ...
  valid_size: ...
  scheduler: ...
  scheduler_params:
    step_size: ...
    gamma: ...

inference:
  batch_size: ...
