general:
  data:
    path: './data/Zzzs_train.parquet'
    excluding_columns: ['series_id', 'timestamp', 'step', 'night', 'event']
  tensorboard:
    path: './tensorboard'
  test_data:
    path: './data/testing2.parquet'