model:
  cnn:
    activation: 'ReLU'
    normalization: 'LayerNorm'
    polling: 'MaxPool1d'
    out_features: '[100, 50, 20]'
    pooling_sizes: '[2]'
    kernel_sizes: '[2]'
    strides: '[2]'
    dilations: '[1]'
    dropout_rates: '[0.4]'
    fc_outputs: '[50, 1]'
    fc_dropout_rates: '[0.4, 0.4]'
