model:
  cnn:
    activation: ...
    normalization: ...
    polling: ...
    out_features: ...
    pooling_sizes: ...
    kernel_sizes: ...
    strides: ...
    dilations: ...
    dropout_rates: ...
    fc_outputs: ...
    fc_dropout_rates: ...
