train:
  model: 'cnn'
  learning_rate: ...
  batch_size: ...
  data:
    scaler: 'StandardScaler'
    shuffle: 'False'
  optimizer: ...
  criterion: ...
  epochs: ...
  valid_size: ...
  scheduler: ...
  scheduler_params:
    step_size: ...
    gamma: ...
