train:
  model: 'LSTM'
  module: 'models.lstm'
  learning_rate: 0.01
  batch_size: 32
  window_size: 5
  data:
    scaler: 'StandardScaler'
    shuffle: 'False'
  optimizer: 'Adam'
  criterion:
    name: 'BCEWithLogitsLoss'
    params:
      reduction: 'mean'
  epochs: 1
  valid_size: 0.2
  scheduler: 'StepLR'
  scheduler_params:
    step_size: 10
    gamma: 0.1