train:
  data:
    scaler: 'StandardScaler'
  model: 'cnn'
  n_features: ...
  seq_len: ...
  batch_size: ...
  optimizer: ...
  criterion: ...
  epochs: ...
  valid_size: ...
  scheduler: ...
  scheduler_params:
    step_size: ...
    gamma: ...
