train:
  model: 'LSTFLinear'
  learning_rate: 0.001
  batch_size: 64
  window_size: 120
  random_seed: 42
  data:
    scaler: 'StandardScaler'
    shuffle: 'False'
  optimizer: 'Adam'
  criterion:
    name: 'CrossEntropyLoss'
    params:
      reduction: 'mean'
  epochs: 5
  patience: 5
  valid_size: 0.2
  scheduler: 'StepLR'
  scheduler_params:
    step_size: 10
    gamma: 0.1