train:
  model: 'TSMixer'
  learning_rate: 0.004
  batch_size: 256
  window_size: 120
  random_seed: 42
  step: 2
  data:
    scaler: 'StandardScaler'
    shuffle: 'False'
  optimizer: 'Adam'
  criterion:
    name: 'BCEWithLogitsLoss'
    params:
      reduction: 'mean'
  epochs: 1
  patience: 5
  valid_size: 0.2
  scheduler: 'StepLR'
  scheduler_params:
    step_size: 10
    gamma: 0.1